; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -verify-machineinstrs -mtriple=armv7-unknown-linux-gnueabi | FileCheck %s --check-prefixes=ARM
; RUN: llc < %s -verify-machineinstrs -mtriple=thumbv7m-none-eabi | FileCheck %s --check-prefixes=THUMB2
; RUN: llc < %s -verify-machineinstrs -mtriple=thumbv6m-none-eabi | FileCheck %s --check-prefixes=THUMB1

define dso_local i32 @skip(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr "zero-call-used-regs"="skip" {
; ARM-LABEL: skip:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: skip:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: skip:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @used_gpr_arg(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr noinline optnone "zero-call-used-regs"="used-gpr-arg" {
; ARM-LABEL: used_gpr_arg:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: used_gpr_arg:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: used_gpr_arg:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @used_gpr(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr noinline optnone "zero-call-used-regs"="used-gpr" {
; ARM-LABEL: used_gpr:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: used_gpr:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: used_gpr:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @used_arg(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr noinline optnone "zero-call-used-regs"="used-arg" {
; ARM-LABEL: used_arg:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: used_arg:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: used_arg:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @used(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr noinline optnone "zero-call-used-regs"="used" {
; ARM-LABEL: used:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: used:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: used:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @all_gpr_arg(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr "zero-call-used-regs"="all-gpr-arg" {
; ARM-LABEL: all_gpr_arg:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    mov r3, #0
; ARM-NEXT:    mov r12, #0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: all_gpr_arg:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    movs r3, #0
; THUMB2-NEXT:    mov.w r12, #0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: all_gpr_arg:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    mov r3, r2
; THUMB1-NEXT:    mov r12, r2
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}

define dso_local i32 @all_gpr(i32 noundef %a, i32 noundef %b, i32 noundef %c) local_unnamed_addr "zero-call-used-regs"="all-gpr" {
; ARM-LABEL: all_gpr:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    mul r0, r1, r0
; ARM-NEXT:    mov r3, #0
; ARM-NEXT:    mov r12, #0
; ARM-NEXT:    orr r0, r0, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB2-LABEL: all_gpr:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    muls r0, r1, r0
; THUMB2-NEXT:    movs r3, #0
; THUMB2-NEXT:    mov.w r12, #0
; THUMB2-NEXT:    orrs r0, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    bx lr
;
; THUMB1-LABEL: all_gpr:
; THUMB1:       @ %bb.0: @ %entry
; THUMB1-NEXT:    muls r0, r1, r0
; THUMB1-NEXT:    orrs r0, r2
; THUMB1-NEXT:    movs r2, #0
; THUMB1-NEXT:    mov r3, r2
; THUMB1-NEXT:    mov r12, r2
; THUMB1-NEXT:    bx lr
entry:
  %mul = mul nsw i32 %b, %a
  %or = or i32 %mul, %c
  ret i32 %or
}
