; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-none-eabi -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv6m-none-eabi -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=THUMB
; RUN: llc -mtriple=thumbv7m-none-eabi -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=T2
; RUN: llc -mtriple=armv7-none-eabi -filetype=obj %s -o /dev/null
; RUN: llc -mtriple=thumbv6m-none-eabi -filetype=obj %s -o /dev/null
; RUN: llc -mtriple=thumbv7m-none-eabi -filetype=obj %s -o /dev/null

; A byte local still owns a word-aligned frame: clearing includes padding.
define i32 @small(i32 %x) "zeroize-stack"="used" {
; ARM-LABEL: small:
; ARM:       @ %bb.0:
; ARM-NEXT:    .pad #4
; ARM-NEXT:    sub sp, sp, #4
; ARM-NEXT:    mov r1, #42
; ARM-NEXT:    strb r1, [sp]
; ARM-NEXT:    mov r1, sp
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    str r2, [r1]
; ARM-NEXT:    add r1, sp, #4
; ARM-NEXT:    mov sp, r1
; ARM-NEXT:    mov r1, #0
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: small:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .pad #4
; THUMB-NEXT:    sub sp, #4
; THUMB-NEXT:    mov r1, sp
; THUMB-NEXT:    movs r2, #42
; THUMB-NEXT:    strb r2, [r1]
; THUMB-NEXT:    movs r2, #0
; THUMB-NEXT:    str r2, [r1]
; THUMB-NEXT:    add r1, sp, #4
; THUMB-NEXT:    mov sp, r1
; THUMB-NEXT:    movs r1, #0
; THUMB-NEXT:    mov r2, r1
; THUMB-NEXT:    bx lr
;
; T2-LABEL: small:
; T2:       @ %bb.0:
; T2-NEXT:    .pad #4
; T2-NEXT:    sub sp, #4
; T2-NEXT:    movs r1, #42
; T2-NEXT:    strb.w r1, [sp]
; T2-NEXT:    mov r1, sp
; T2-NEXT:    movs r2, #0
; T2-NEXT:    str r2, [r1]
; T2-NEXT:    adds r1, #4
; T2-NEXT:    mov sp, r1
; T2-NEXT:    movs r1, #0
; T2-NEXT:    movs r2, #0
; T2-NEXT:    bx lr
  %p = alloca i8, align 4
  store volatile i8 42, ptr %p
  ret i32 %x
}

; Clearing-created temporaries must be erased even with explicit skip.
; Restores of low/high callee-saved registers and LR precede frame erasure.
declare void @consume(ptr)
define i32 @saved(i32 %x) "zeroize-stack"="used" "zero-call-used-regs"="skip" {
; ARM-LABEL: saved:
; ARM:       @ %bb.0:
; ARM-NEXT:    .save {r4, r8, r11, lr}
; ARM-NEXT:    push {r4, r8, r11, lr}
; ARM-NEXT:    .pad #24
; ARM-NEXT:    sub sp, sp, #24
; ARM-NEXT:    str r0, [sp, #4]
; ARM-NEXT:    add r0, sp, #4
; ARM-NEXT:    bl consume
; ARM-NEXT:    @APP
; ARM-NEXT:    @NO_APP
; ARM-NEXT:    ldr r0, [sp, #4]
; ARM-NEXT:    add r1, sp, #36
; ARM-NEXT:    ldr lr, [r1] @ 4-byte Reload
; ARM-NEXT:    add r1, sp, #32
; ARM-NEXT:    ldr r11, [r1] @ 4-byte Reload
; ARM-NEXT:    add r1, sp, #28
; ARM-NEXT:    ldr r8, [r1] @ 4-byte Reload
; ARM-NEXT:    add r1, sp, #24
; ARM-NEXT:    ldr r4, [r1] @ 4-byte Reload
; ARM-NEXT:    mov r1, sp
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    str r2, [r1]
; ARM-NEXT:    str r2, [r1, #4]
; ARM-NEXT:    str r2, [r1, #8]
; ARM-NEXT:    str r2, [r1, #12]
; ARM-NEXT:    str r2, [r1, #16]
; ARM-NEXT:    str r2, [r1, #20]
; ARM-NEXT:    str r2, [r1, #24]
; ARM-NEXT:    str r2, [r1, #28]
; ARM-NEXT:    str r2, [r1, #32]
; ARM-NEXT:    str r2, [r1, #36]
; ARM-NEXT:    add r1, sp, #40
; ARM-NEXT:    mov sp, r1
; ARM-NEXT:    mov r1, #0
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: saved:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .save {r4, lr}
; THUMB-NEXT:    push {r4, lr}
; THUMB-NEXT:    mov lr, r11
; THUMB-NEXT:    mov r4, r8
; THUMB-NEXT:    .save {r8, r11}
; THUMB-NEXT:    push {r4, lr}
; THUMB-NEXT:    .pad #24
; THUMB-NEXT:    sub sp, #24
; THUMB-NEXT:    str r0, [sp, #4]
; THUMB-NEXT:    add r0, sp, #4
; THUMB-NEXT:    bl consume
; THUMB-NEXT:    @APP
; THUMB-NEXT:    @NO_APP
; THUMB-NEXT:    ldr r0, [sp, #4]
; THUMB-NEXT:    add r1, sp, #36
; THUMB-NEXT:    ldr r2, [r1] @ 4-byte Reload
; THUMB-NEXT:    mov lr, r2
; THUMB-NEXT:    add r1, sp, #32
; THUMB-NEXT:    ldr r4, [r1] @ 4-byte Reload
; THUMB-NEXT:    add r1, sp, #28
; THUMB-NEXT:    ldr r2, [r1] @ 4-byte Reload
; THUMB-NEXT:    mov r11, r2
; THUMB-NEXT:    add r1, sp, #24
; THUMB-NEXT:    ldr r2, [r1] @ 4-byte Reload
; THUMB-NEXT:    mov r8, r2
; THUMB-NEXT:    mov r1, sp
; THUMB-NEXT:    movs r2, #0
; THUMB-NEXT:    str r2, [r1]
; THUMB-NEXT:    str r2, [r1, #4]
; THUMB-NEXT:    str r2, [r1, #8]
; THUMB-NEXT:    str r2, [r1, #12]
; THUMB-NEXT:    str r2, [r1, #16]
; THUMB-NEXT:    str r2, [r1, #20]
; THUMB-NEXT:    str r2, [r1, #24]
; THUMB-NEXT:    str r2, [r1, #28]
; THUMB-NEXT:    str r2, [r1, #32]
; THUMB-NEXT:    str r2, [r1, #36]
; THUMB-NEXT:    add r1, sp, #40
; THUMB-NEXT:    mov sp, r1
; THUMB-NEXT:    movs r1, #0
; THUMB-NEXT:    mov r2, r1
; THUMB-NEXT:    bx lr
;
; T2-LABEL: saved:
; T2:       @ %bb.0:
; T2-NEXT:    .save {r4, r8, r11, lr}
; T2-NEXT:    push.w {r4, r8, r11, lr}
; T2-NEXT:    .pad #24
; T2-NEXT:    sub sp, #24
; T2-NEXT:    str r0, [sp, #4]
; T2-NEXT:    add r0, sp, #4
; T2-NEXT:    bl consume
; T2-NEXT:    @APP
; T2-NEXT:    @NO_APP
; T2-NEXT:    ldr r0, [sp, #4]
; T2-NEXT:    mov r1, sp
; T2-NEXT:    adds r1, #36
; T2-NEXT:    ldr.w lr, [r1] @ 4-byte Reload
; T2-NEXT:    mov r1, sp
; T2-NEXT:    adds r1, #32
; T2-NEXT:    ldr.w r11, [r1] @ 4-byte Reload
; T2-NEXT:    mov r1, sp
; T2-NEXT:    adds r1, #28
; T2-NEXT:    ldr.w r8, [r1] @ 4-byte Reload
; T2-NEXT:    mov r1, sp
; T2-NEXT:    adds r1, #24
; T2-NEXT:    ldr r4, [r1] @ 4-byte Reload
; T2-NEXT:    mov r1, sp
; T2-NEXT:    movs r2, #0
; T2-NEXT:    str r2, [r1]
; T2-NEXT:    str r2, [r1, #4]
; T2-NEXT:    str r2, [r1, #8]
; T2-NEXT:    str r2, [r1, #12]
; T2-NEXT:    str r2, [r1, #16]
; T2-NEXT:    str r2, [r1, #20]
; T2-NEXT:    str r2, [r1, #24]
; T2-NEXT:    str r2, [r1, #28]
; T2-NEXT:    str r2, [r1, #32]
; T2-NEXT:    str r2, [r1, #36]
; T2-NEXT:    adds r1, #40
; T2-NEXT:    mov sp, r1
; T2-NEXT:    movs r1, #0
; T2-NEXT:    movs r2, #0
; T2-NEXT:    bx lr
  %p = alloca [20 x i8], align 4
  store volatile i32 %x, ptr %p
  call void @consume(ptr %p)
  call void asm sideeffect "", "~{r4},~{r8},~{r11}"()
  %v = load volatile i32, ptr %p
  ret i32 %v
}

; A large frame uses a bounded loop, retaining the i64 return in r0:r1.
define i64 @large(i64 %x) "zeroize-stack"="sensitive" "zero-call-used-regs"="used-gpr" {
; ARM-LABEL: large:
; ARM:       @ %bb.0:
; ARM-NEXT:    .save {r4, r5}
; ARM-NEXT:    push {r4, r5}
; ARM-NEXT:    .pad #4
; ARM-NEXT:    sub sp, sp, #4
; ARM-NEXT:    .pad #8192
; ARM-NEXT:    sub sp, sp, #8192
; ARM-NEXT:    mov r2, #42
; ARM-NEXT:    strb r2, [sp]
; ARM-NEXT:    add r2, sp, #8
; ARM-NEXT:    add r2, r2, #8192
; ARM-NEXT:    ldr r5, [r2] @ 4-byte Reload
; ARM-NEXT:    add r2, sp, #4
; ARM-NEXT:    add r2, r2, #8192
; ARM-NEXT:    ldr r4, [r2] @ 4-byte Reload
; ARM-NEXT:    add r3, sp, #12
; ARM-NEXT:    mov r2, sp
; ARM-NEXT:    add r3, r3, #8192
; ARM-NEXT:    mov r12, r3
; ARM-NEXT:    mov r3, #0
; ARM-NEXT:  .LBB2_1: @ =>This Inner Loop Header: Depth=1
; ARM-NEXT:    str r3, [r2]
; ARM-NEXT:    add r2, r2, #4
; ARM-NEXT:    cmp r2, r12
; ARM-NEXT:    bne .LBB2_1
; ARM-NEXT:  @ %bb.2:
; ARM-NEXT:    mov sp, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    mov r3, #0
; ARM-NEXT:    mov r12, #0
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: large:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .save {r4, r5, r6, lr}
; THUMB-NEXT:    push {r4, r5, r6, lr}
; THUMB-NEXT:    ldr r6, .LCPI2_0
; THUMB-NEXT:    .pad #8196
; THUMB-NEXT:    add sp, r6
; THUMB-NEXT:    mov r2, sp
; THUMB-NEXT:    movs r3, #42
; THUMB-NEXT:    strb r3, [r2]
; THUMB-NEXT:    ldr r2, .LCPI2_1
; THUMB-NEXT:    add r2, sp
; THUMB-NEXT:    ldr r3, [r2] @ 4-byte Reload
; THUMB-NEXT:    mov lr, r3
; THUMB-NEXT:    ldr r2, .LCPI2_2
; THUMB-NEXT:    add r2, sp
; THUMB-NEXT:    ldr r6, [r2] @ 4-byte Reload
; THUMB-NEXT:    ldr r2, .LCPI2_3
; THUMB-NEXT:    add r2, sp
; THUMB-NEXT:    ldr r5, [r2] @ 4-byte Reload
; THUMB-NEXT:    ldr r2, .LCPI2_4
; THUMB-NEXT:    add r2, sp
; THUMB-NEXT:    ldr r4, [r2] @ 4-byte Reload
; THUMB-NEXT:    mov r2, sp
; THUMB-NEXT:    ldr r3, .LCPI2_5
; THUMB-NEXT:    add r3, sp
; THUMB-NEXT:    mov r12, r3
; THUMB-NEXT:    movs r3, #0
; THUMB-NEXT:  .LBB2_1: @ =>This Inner Loop Header: Depth=1
; THUMB-NEXT:    str r3, [r2]
; THUMB-NEXT:    adds r2, #4
; THUMB-NEXT:    cmp r2, r12
; THUMB-NEXT:    bne .LBB2_1
; THUMB-NEXT:  @ %bb.2:
; THUMB-NEXT:    mov sp, r2
; THUMB-NEXT:    movs r2, #0
; THUMB-NEXT:    mov r3, r2
; THUMB-NEXT:    mov r12, r2
; THUMB-NEXT:    bx lr
; THUMB-NEXT:    .p2align 2
; THUMB-NEXT:  @ %bb.3:
; THUMB-NEXT:  .LCPI2_0:
; THUMB-NEXT:    .long 4294959100 @ 0xffffdffc
; THUMB-NEXT:  .LCPI2_1:
; THUMB-NEXT:    .long 8208 @ 0x2010
; THUMB-NEXT:  .LCPI2_2:
; THUMB-NEXT:    .long 8204 @ 0x200c
; THUMB-NEXT:  .LCPI2_3:
; THUMB-NEXT:    .long 8200 @ 0x2008
; THUMB-NEXT:  .LCPI2_4:
; THUMB-NEXT:    .long 8196 @ 0x2004
; THUMB-NEXT:  .LCPI2_5:
; THUMB-NEXT:    .long 8212 @ 0x2014
;
; T2-LABEL: large:
; T2:       @ %bb.0:
; T2-NEXT:    .save {r4, r5}
; T2-NEXT:    push {r4, r5}
; T2-NEXT:    .pad #8192
; T2-NEXT:    sub.w sp, sp, #8192
; T2-NEXT:    .pad #4
; T2-NEXT:    sub sp, #4
; T2-NEXT:    movs r2, #42
; T2-NEXT:    strb.w r2, [sp]
; T2-NEXT:    mov r2, sp
; T2-NEXT:    add.w r2, r2, #8192
; T2-NEXT:    adds r2, #8
; T2-NEXT:    ldr r5, [r2] @ 4-byte Reload
; T2-NEXT:    mov r2, sp
; T2-NEXT:    add.w r2, r2, #8192
; T2-NEXT:    ldr r4, [r2, #4]! @ 4-byte Reload
; T2-NEXT:    mov r3, sp
; T2-NEXT:    mov r2, sp
; T2-NEXT:    add.w r3, r3, #8192
; T2-NEXT:    adds r3, #12
; T2-NEXT:    mov r12, r3
; T2-NEXT:    movs r3, #0
; T2-NEXT:  .LBB2_1: @ =>This Inner Loop Header: Depth=1
; T2-NEXT:    str r3, [r2]
; T2-NEXT:    adds r2, #4
; T2-NEXT:    cmp r2, r12
; T2-NEXT:    bne .LBB2_1
; T2-NEXT:  @ %bb.2:
; T2-NEXT:    mov sp, r2
; T2-NEXT:    movs r2, #0
; T2-NEXT:    movs r3, #0
; T2-NEXT:    mov.w r12, #0
; T2-NEXT:    bx lr
  %p = alloca [8193 x i8], align 4
  store volatile i8 42, ptr %p
  ret i64 %x
}

; Empty frames need neither stores nor scratch registers.
define i32 @empty(i32 %x) "zeroize-stack"="used" {
; ARM-LABEL: empty:
; ARM:       @ %bb.0:
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: empty:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    bx lr
;
; T2-LABEL: empty:
; T2:       @ %bb.0:
; T2-NEXT:    bx lr
  ret i32 %x
}

; Low-half-zero offsets must not reuse stale bits in the addressing scratch.
define i32 @large_offset(i32 %x) "zeroize-stack"="used" {
; ARM-LABEL: large_offset:
; ARM:       @ %bb.0:
; ARM-NEXT:    .save {r4, r5}
; ARM-NEXT:    push {r4, r5}
; ARM-NEXT:    .pad #36962304
; ARM-NEXT:    sub sp, sp, #36962304
; ARM-NEXT:    .pad #268435456
; ARM-NEXT:    sub sp, sp, #268435456
; ARM-NEXT:    mov r1, #42
; ARM-NEXT:    strb r1, [sp]
; ARM-NEXT:    add r1, sp, #4
; ARM-NEXT:    add r1, r1, #36962304
; ARM-NEXT:    add r1, r1, #268435456
; ARM-NEXT:    ldr r5, [r1] @ 4-byte Reload
; ARM-NEXT:    add r1, sp, #36962304
; ARM-NEXT:    add r1, r1, #268435456
; ARM-NEXT:    ldr r4, [r1] @ 4-byte Reload
; ARM-NEXT:    add r2, sp, #8
; ARM-NEXT:    mov r1, sp
; ARM-NEXT:    add r2, r2, #36962304
; ARM-NEXT:    add r2, r2, #268435456
; ARM-NEXT:    mov r12, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:  .LBB4_1: @ =>This Inner Loop Header: Depth=1
; ARM-NEXT:    str r2, [r1]
; ARM-NEXT:    add r1, r1, #4
; ARM-NEXT:    cmp r1, r12
; ARM-NEXT:    bne .LBB4_1
; ARM-NEXT:  @ %bb.2:
; ARM-NEXT:    mov sp, r1
; ARM-NEXT:    mov r1, #0
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    mov r12, #0
; ARM-NEXT:    bx lr
;
; THUMB-LABEL: large_offset:
; THUMB:       @ %bb.0:
; THUMB-NEXT:    .save {r4, r5, r6, lr}
; THUMB-NEXT:    push {r4, r5, r6, lr}
; THUMB-NEXT:    ldr r6, .LCPI4_0
; THUMB-NEXT:    .pad #305397760
; THUMB-NEXT:    add sp, r6
; THUMB-NEXT:    mov r1, sp
; THUMB-NEXT:    movs r2, #42
; THUMB-NEXT:    strb r2, [r1]
; THUMB-NEXT:    ldr r1, .LCPI4_1
; THUMB-NEXT:    add r1, sp
; THUMB-NEXT:    ldr r2, [r1] @ 4-byte Reload
; THUMB-NEXT:    mov lr, r2
; THUMB-NEXT:    ldr r1, .LCPI4_2
; THUMB-NEXT:    add r1, sp
; THUMB-NEXT:    ldr r6, [r1] @ 4-byte Reload
; THUMB-NEXT:    ldr r1, .LCPI4_3
; THUMB-NEXT:    add r1, sp
; THUMB-NEXT:    ldr r5, [r1] @ 4-byte Reload
; THUMB-NEXT:    ldr r1, .LCPI4_4
; THUMB-NEXT:    add r1, sp
; THUMB-NEXT:    ldr r4, [r1] @ 4-byte Reload
; THUMB-NEXT:    mov r1, sp
; THUMB-NEXT:    ldr r2, .LCPI4_5
; THUMB-NEXT:    add r2, sp
; THUMB-NEXT:    mov r12, r2
; THUMB-NEXT:    movs r2, #0
; THUMB-NEXT:  .LBB4_1: @ =>This Inner Loop Header: Depth=1
; THUMB-NEXT:    str r2, [r1]
; THUMB-NEXT:    adds r1, #4
; THUMB-NEXT:    cmp r1, r12
; THUMB-NEXT:    bne .LBB4_1
; THUMB-NEXT:  @ %bb.2:
; THUMB-NEXT:    mov sp, r1
; THUMB-NEXT:    movs r1, #0
; THUMB-NEXT:    mov r2, r1
; THUMB-NEXT:    mov r12, r1
; THUMB-NEXT:    bx lr
; THUMB-NEXT:    .p2align 2
; THUMB-NEXT:  @ %bb.3:
; THUMB-NEXT:  .LCPI4_0:
; THUMB-NEXT:    .long 3989569536 @ 0xedcc0000
; THUMB-NEXT:  .LCPI4_1:
; THUMB-NEXT:    .long 305397772 @ 0x1234000c
; THUMB-NEXT:  .LCPI4_2:
; THUMB-NEXT:    .long 305397768 @ 0x12340008
; THUMB-NEXT:  .LCPI4_3:
; THUMB-NEXT:    .long 305397764 @ 0x12340004
; THUMB-NEXT:  .LCPI4_4:
; THUMB-NEXT:    .long 305397760 @ 0x12340000
; THUMB-NEXT:  .LCPI4_5:
; THUMB-NEXT:    .long 305397776 @ 0x12340010
;
; T2-LABEL: large_offset:
; T2:       @ %bb.0:
; T2-NEXT:    .save {r4, r5}
; T2-NEXT:    push {r4, r5}
; T2-NEXT:    .pad #304087040
; T2-NEXT:    sub.w sp, sp, #304087040
; T2-NEXT:    .pad #1310720
; T2-NEXT:    sub.w sp, sp, #1310720
; T2-NEXT:    movs r1, #42
; T2-NEXT:    strb.w r1, [sp]
; T2-NEXT:    mov r1, sp
; T2-NEXT:    add.w r1, r1, #304087040
; T2-NEXT:    add.w r1, r1, #1310720
; T2-NEXT:    ldr r5, [r1, #4]! @ 4-byte Reload
; T2-NEXT:    mov r1, sp
; T2-NEXT:    add.w r1, r1, #304087040
; T2-NEXT:    add.w r1, r1, #1310720
; T2-NEXT:    ldr r4, [r1] @ 4-byte Reload
; T2-NEXT:    mov r2, sp
; T2-NEXT:    mov r1, sp
; T2-NEXT:    add.w r2, r2, #304087040
; T2-NEXT:    add.w r2, r2, #1310720
; T2-NEXT:    adds r2, #8
; T2-NEXT:    mov r12, r2
; T2-NEXT:    movs r2, #0
; T2-NEXT:  .LBB4_1: @ =>This Inner Loop Header: Depth=1
; T2-NEXT:    str r2, [r1]
; T2-NEXT:    adds r1, #4
; T2-NEXT:    cmp r1, r12
; T2-NEXT:    bne .LBB4_1
; T2-NEXT:  @ %bb.2:
; T2-NEXT:    mov sp, r1
; T2-NEXT:    movs r1, #0
; T2-NEXT:    movs r2, #0
; T2-NEXT:    mov.w r12, #0
; T2-NEXT:    bx lr
  %p = alloca [305397760 x i8], align 4
  store volatile i8 42, ptr %p
  ret i32 %x
}
