; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=thumbv8m.base-none-eabi -mattr=+8msecext -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=BASE
; RUN: llc -mtriple=thumbv8m.base-none-eabi -mattr=+8msecext -O0 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=BASE
; RUN: llc -mtriple=thumbv8m.main-none-eabi -mattr=+8msecext,-fpregs -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=MAIN
; RUN: llc -mtriple=thumbv8m.main-none-eabi -mattr=+8msecext,+fp-armv8d16sp -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=FP
; RUN: llc -mtriple=thumbv8m.main-none-eabi -mattr=+8msecext,+fp-armv8d16sp -mcp-use-is-copy-instr -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=FP
; RUN: llc -mtriple=thumbv8m.main-none-eabi -mattr=+8msecext,+fp-armv8d16sp -O0 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=FP-O0
; RUN: llc -mtriple=thumbv8.1m.main-none-eabi -mattr=+8msecext -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=V81

; A CMSE return clears R0-R3 and R12, other than the return value, and the
; flags, and S0-S15 when secure code has used the FPU. Before v8.1-M it does so
; by copying LR. When the function asks for register clearing, PEI leaves
; those GPRs to the expansion and marks the return with an implicit R12 use,
; and the expansion copies a zeroed R12 instead, so every cleared register is
; zero at the bxns. R12 is zeroed after its last use as CMSE scratch. PEI still
; clears the FP registers itself, because the expansion skips them when the
; FPU is inactive in the secure state.

define i32 @all_gpr(i32 %x) "cmse_nonsecure_entry" "zero-call-used-regs"="all-gpr" {
; BASE-LABEL: all_gpr:
; BASE:       @ %bb.0:
; BASE-NEXT:    movw r12, #0
; BASE-NEXT:    mov r1, r12
; BASE-NEXT:    mov r2, r12
; BASE-NEXT:    mov r3, r12
; BASE-NEXT:    msr apsr, r12
; BASE-NEXT:    bxns lr
;
; MAIN-LABEL: all_gpr:
; MAIN:       @ %bb.0:
; MAIN-NEXT:    mov.w r12, #0
; MAIN-NEXT:    mov r1, r12
; MAIN-NEXT:    mov r2, r12
; MAIN-NEXT:    mov r3, r12
; MAIN-NEXT:    msr apsr_nzcvq, r12
; MAIN-NEXT:    bxns lr
;
; FP-LABEL: all_gpr:
; FP:       @ %bb.0:
; FP-NEXT:    mrs r12, control
; FP-NEXT:    tst.w r12, #8
; FP-NEXT:    beq .LBB0_2
; FP-NEXT:  @ %bb.1:
; FP-NEXT:    vmrs r12, fpscr
; FP-NEXT:    bic r12, r12, #159
; FP-NEXT:    bic r12, r12, #4026531840
; FP-NEXT:    vmsr fpscr, r12
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    vmov d0, r12, r12
; FP-NEXT:    vmov d1, r12, r12
; FP-NEXT:    vmov d2, r12, r12
; FP-NEXT:    vmov d3, r12, r12
; FP-NEXT:    vmov d4, r12, r12
; FP-NEXT:    vmov d5, r12, r12
; FP-NEXT:    vmov d6, r12, r12
; FP-NEXT:    vmov d7, r12, r12
; FP-NEXT:  .LBB0_2:
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    mov r1, r12
; FP-NEXT:    mov r2, r12
; FP-NEXT:    mov r3, r12
; FP-NEXT:    msr apsr_nzcvq, r12
; FP-NEXT:    bxns lr
;
; FP-O0-LABEL: all_gpr:
; FP-O0:       @ %bb.0:
; FP-O0-NEXT:    mrs r12, control
; FP-O0-NEXT:    tst.w r12, #8
; FP-O0-NEXT:    beq .LBB0_2
; FP-O0-NEXT:  @ %bb.1:
; FP-O0-NEXT:    vmrs r12, fpscr
; FP-O0-NEXT:    bic r12, r12, #159
; FP-O0-NEXT:    bic r12, r12, #4026531840
; FP-O0-NEXT:    vmsr fpscr, r12
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    vmov d0, r12, r12
; FP-O0-NEXT:    vmov d1, r12, r12
; FP-O0-NEXT:    vmov d2, r12, r12
; FP-O0-NEXT:    vmov d3, r12, r12
; FP-O0-NEXT:    vmov d4, r12, r12
; FP-O0-NEXT:    vmov d5, r12, r12
; FP-O0-NEXT:    vmov d6, r12, r12
; FP-O0-NEXT:    vmov d7, r12, r12
; FP-O0-NEXT:  .LBB0_2:
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    mov r1, r12
; FP-O0-NEXT:    mov r2, r12
; FP-O0-NEXT:    mov r3, r12
; FP-O0-NEXT:    msr apsr_nzcvq, r12
; FP-O0-NEXT:    bxns lr
;
; V81-LABEL: all_gpr:
; V81:       @ %bb.0:
; V81-NEXT:    vstr fpcxtns, [sp, #-4]!
; V81-NEXT:    vscclrm {s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, vpr}
; V81-NEXT:    vldr fpcxtns, [sp], #4
; V81-NEXT:    clrm {r1, r2, r3, r12, apsr}
; V81-NEXT:    bxns lr
  ret i32 %x
}

define i32 @all_regs(i32 %x) "cmse_nonsecure_entry" "zero-call-used-regs"="all" {
; BASE-LABEL: all_regs:
; BASE:       @ %bb.0:
; BASE-NEXT:    movw r12, #0
; BASE-NEXT:    mov r1, r12
; BASE-NEXT:    mov r2, r12
; BASE-NEXT:    mov r3, r12
; BASE-NEXT:    msr apsr, r12
; BASE-NEXT:    bxns lr
;
; MAIN-LABEL: all_regs:
; MAIN:       @ %bb.0:
; MAIN-NEXT:    mov.w r12, #0
; MAIN-NEXT:    mov r1, r12
; MAIN-NEXT:    mov r2, r12
; MAIN-NEXT:    mov r3, r12
; MAIN-NEXT:    msr apsr_nzcvq, r12
; MAIN-NEXT:    bxns lr
;
; FP-LABEL: all_regs:
; FP:       @ %bb.0:
; FP-NEXT:    movs r1, #0
; FP-NEXT:    mrs r12, control
; FP-NEXT:    tst.w r12, #8
; FP-NEXT:    vmov d0, r1, r1
; FP-NEXT:    vmov d1, r1, r1
; FP-NEXT:    vmov d2, r1, r1
; FP-NEXT:    vmov d3, r1, r1
; FP-NEXT:    vmov d4, r1, r1
; FP-NEXT:    vmov d5, r1, r1
; FP-NEXT:    vmov d6, r1, r1
; FP-NEXT:    vmov d7, r1, r1
; FP-NEXT:    beq .LBB1_2
; FP-NEXT:  @ %bb.1:
; FP-NEXT:    vmrs r12, fpscr
; FP-NEXT:    bic r12, r12, #159
; FP-NEXT:    bic r12, r12, #4026531840
; FP-NEXT:    vmsr fpscr, r12
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    vmov d0, r12, r12
; FP-NEXT:    vmov d1, r12, r12
; FP-NEXT:    vmov d2, r12, r12
; FP-NEXT:    vmov d3, r12, r12
; FP-NEXT:    vmov d4, r12, r12
; FP-NEXT:    vmov d5, r12, r12
; FP-NEXT:    vmov d6, r12, r12
; FP-NEXT:    vmov d7, r12, r12
; FP-NEXT:  .LBB1_2:
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    mov r1, r12
; FP-NEXT:    mov r2, r12
; FP-NEXT:    mov r3, r12
; FP-NEXT:    msr apsr_nzcvq, r12
; FP-NEXT:    bxns lr
;
; FP-O0-LABEL: all_regs:
; FP-O0:       @ %bb.0:
; FP-O0-NEXT:    movs r1, #0
; FP-O0-NEXT:    vmov d0, r1, r1
; FP-O0-NEXT:    vmov d1, r1, r1
; FP-O0-NEXT:    vmov d2, r1, r1
; FP-O0-NEXT:    vmov d3, r1, r1
; FP-O0-NEXT:    vmov d4, r1, r1
; FP-O0-NEXT:    vmov d5, r1, r1
; FP-O0-NEXT:    vmov d6, r1, r1
; FP-O0-NEXT:    vmov d7, r1, r1
; FP-O0-NEXT:    mrs r12, control
; FP-O0-NEXT:    tst.w r12, #8
; FP-O0-NEXT:    beq .LBB1_2
; FP-O0-NEXT:  @ %bb.1:
; FP-O0-NEXT:    vmrs r12, fpscr
; FP-O0-NEXT:    bic r12, r12, #159
; FP-O0-NEXT:    bic r12, r12, #4026531840
; FP-O0-NEXT:    vmsr fpscr, r12
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    vmov d0, r12, r12
; FP-O0-NEXT:    vmov d1, r12, r12
; FP-O0-NEXT:    vmov d2, r12, r12
; FP-O0-NEXT:    vmov d3, r12, r12
; FP-O0-NEXT:    vmov d4, r12, r12
; FP-O0-NEXT:    vmov d5, r12, r12
; FP-O0-NEXT:    vmov d6, r12, r12
; FP-O0-NEXT:    vmov d7, r12, r12
; FP-O0-NEXT:  .LBB1_2:
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    mov r1, r12
; FP-O0-NEXT:    mov r2, r12
; FP-O0-NEXT:    mov r3, r12
; FP-O0-NEXT:    msr apsr_nzcvq, r12
; FP-O0-NEXT:    bxns lr
;
; V81-LABEL: all_regs:
; V81:       @ %bb.0:
; V81-NEXT:    vstr fpcxtns, [sp, #-4]!
; V81-NEXT:    vscclrm {s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, vpr}
; V81-NEXT:    vldr fpcxtns, [sp], #4
; V81-NEXT:    clrm {r1, r2, r3, r12, apsr}
; V81-NEXT:    bxns lr
  ret i32 %x
}

; Minsize clears the FP registers without testing CONTROL.SFPA.
define i32 @used_r12(i32 %x) minsize "cmse_nonsecure_entry" "zero-call-used-regs"="used-gpr" {
; BASE-LABEL: used_r12:
; BASE:       @ %bb.0:
; BASE-NEXT:    @APP
; BASE-NEXT:    @NO_APP
; BASE-NEXT:    movw r12, #0
; BASE-NEXT:    mov r1, r12
; BASE-NEXT:    mov r2, r12
; BASE-NEXT:    mov r3, r12
; BASE-NEXT:    msr apsr, r12
; BASE-NEXT:    bxns lr
;
; MAIN-LABEL: used_r12:
; MAIN:       @ %bb.0:
; MAIN-NEXT:    @APP
; MAIN-NEXT:    @NO_APP
; MAIN-NEXT:    mov.w r12, #0
; MAIN-NEXT:    mov r1, r12
; MAIN-NEXT:    mov r2, r12
; MAIN-NEXT:    mov r3, r12
; MAIN-NEXT:    msr apsr_nzcvq, r12
; MAIN-NEXT:    bxns lr
;
; FP-LABEL: used_r12:
; FP:       @ %bb.0:
; FP-NEXT:    @APP
; FP-NEXT:    @NO_APP
; FP-NEXT:    vmrs r12, fpscr
; FP-NEXT:    bic r12, r12, #159
; FP-NEXT:    bic r12, r12, #4026531840
; FP-NEXT:    vmsr fpscr, r12
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    vmov d0, r12, r12
; FP-NEXT:    vmov d1, r12, r12
; FP-NEXT:    vmov d2, r12, r12
; FP-NEXT:    vmov d3, r12, r12
; FP-NEXT:    vmov d4, r12, r12
; FP-NEXT:    vmov d5, r12, r12
; FP-NEXT:    vmov d6, r12, r12
; FP-NEXT:    vmov d7, r12, r12
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    mov r1, r12
; FP-NEXT:    mov r2, r12
; FP-NEXT:    mov r3, r12
; FP-NEXT:    msr apsr_nzcvq, r12
; FP-NEXT:    bxns lr
;
; FP-O0-LABEL: used_r12:
; FP-O0:       @ %bb.0:
; FP-O0-NEXT:    @APP
; FP-O0-NEXT:    @NO_APP
; FP-O0-NEXT:    vmrs r12, fpscr
; FP-O0-NEXT:    bic r12, r12, #159
; FP-O0-NEXT:    bic r12, r12, #4026531840
; FP-O0-NEXT:    vmsr fpscr, r12
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    vmov d0, r12, r12
; FP-O0-NEXT:    vmov d1, r12, r12
; FP-O0-NEXT:    vmov d2, r12, r12
; FP-O0-NEXT:    vmov d3, r12, r12
; FP-O0-NEXT:    vmov d4, r12, r12
; FP-O0-NEXT:    vmov d5, r12, r12
; FP-O0-NEXT:    vmov d6, r12, r12
; FP-O0-NEXT:    vmov d7, r12, r12
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    mov r1, r12
; FP-O0-NEXT:    mov r2, r12
; FP-O0-NEXT:    mov r3, r12
; FP-O0-NEXT:    msr apsr_nzcvq, r12
; FP-O0-NEXT:    bxns lr
;
; V81-LABEL: used_r12:
; V81:       @ %bb.0:
; V81-NEXT:    vstr fpcxtns, [sp, #-4]!
; V81-NEXT:    @APP
; V81-NEXT:    @NO_APP
; V81-NEXT:    vscclrm {s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, vpr}
; V81-NEXT:    vldr fpcxtns, [sp], #4
; V81-NEXT:    clrm {r1, r2, r3, r12, apsr}
; V81-NEXT:    bxns lr
  call void asm sideeffect "", "~{r12}"()
  ret i32 %x
}

; A 64-bit return keeps both r0 and r1.
define i64 @all_i64(i64 %x) "cmse_nonsecure_entry" "zero-call-used-regs"="all" {
; BASE-LABEL: all_i64:
; BASE:       @ %bb.0:
; BASE-NEXT:    movw r12, #0
; BASE-NEXT:    mov r2, r12
; BASE-NEXT:    mov r3, r12
; BASE-NEXT:    msr apsr, r12
; BASE-NEXT:    bxns lr
;
; MAIN-LABEL: all_i64:
; MAIN:       @ %bb.0:
; MAIN-NEXT:    mov.w r12, #0
; MAIN-NEXT:    mov r2, r12
; MAIN-NEXT:    mov r3, r12
; MAIN-NEXT:    msr apsr_nzcvq, r12
; MAIN-NEXT:    bxns lr
;
; FP-LABEL: all_i64:
; FP:       @ %bb.0:
; FP-NEXT:    movs r2, #0
; FP-NEXT:    mrs r12, control
; FP-NEXT:    tst.w r12, #8
; FP-NEXT:    vmov d0, r2, r2
; FP-NEXT:    vmov d1, r2, r2
; FP-NEXT:    vmov d2, r2, r2
; FP-NEXT:    vmov d3, r2, r2
; FP-NEXT:    vmov d4, r2, r2
; FP-NEXT:    vmov d5, r2, r2
; FP-NEXT:    vmov d6, r2, r2
; FP-NEXT:    vmov d7, r2, r2
; FP-NEXT:    beq .LBB3_2
; FP-NEXT:  @ %bb.1:
; FP-NEXT:    vmrs r12, fpscr
; FP-NEXT:    bic r12, r12, #159
; FP-NEXT:    bic r12, r12, #4026531840
; FP-NEXT:    vmsr fpscr, r12
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    vmov d0, r12, r12
; FP-NEXT:    vmov d1, r12, r12
; FP-NEXT:    vmov d2, r12, r12
; FP-NEXT:    vmov d3, r12, r12
; FP-NEXT:    vmov d4, r12, r12
; FP-NEXT:    vmov d5, r12, r12
; FP-NEXT:    vmov d6, r12, r12
; FP-NEXT:    vmov d7, r12, r12
; FP-NEXT:  .LBB3_2:
; FP-NEXT:    mov.w r12, #0
; FP-NEXT:    mov r2, r12
; FP-NEXT:    mov r3, r12
; FP-NEXT:    msr apsr_nzcvq, r12
; FP-NEXT:    bxns lr
;
; FP-O0-LABEL: all_i64:
; FP-O0:       @ %bb.0:
; FP-O0-NEXT:    movs r2, #0
; FP-O0-NEXT:    vmov d0, r2, r2
; FP-O0-NEXT:    vmov d1, r2, r2
; FP-O0-NEXT:    vmov d2, r2, r2
; FP-O0-NEXT:    vmov d3, r2, r2
; FP-O0-NEXT:    vmov d4, r2, r2
; FP-O0-NEXT:    vmov d5, r2, r2
; FP-O0-NEXT:    vmov d6, r2, r2
; FP-O0-NEXT:    vmov d7, r2, r2
; FP-O0-NEXT:    mrs r12, control
; FP-O0-NEXT:    tst.w r12, #8
; FP-O0-NEXT:    beq .LBB3_2
; FP-O0-NEXT:  @ %bb.1:
; FP-O0-NEXT:    vmrs r12, fpscr
; FP-O0-NEXT:    bic r12, r12, #159
; FP-O0-NEXT:    bic r12, r12, #4026531840
; FP-O0-NEXT:    vmsr fpscr, r12
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    vmov d0, r12, r12
; FP-O0-NEXT:    vmov d1, r12, r12
; FP-O0-NEXT:    vmov d2, r12, r12
; FP-O0-NEXT:    vmov d3, r12, r12
; FP-O0-NEXT:    vmov d4, r12, r12
; FP-O0-NEXT:    vmov d5, r12, r12
; FP-O0-NEXT:    vmov d6, r12, r12
; FP-O0-NEXT:    vmov d7, r12, r12
; FP-O0-NEXT:  .LBB3_2:
; FP-O0-NEXT:    mov.w r12, #0
; FP-O0-NEXT:    mov r2, r12
; FP-O0-NEXT:    mov r3, r12
; FP-O0-NEXT:    msr apsr_nzcvq, r12
; FP-O0-NEXT:    bxns lr
;
; V81-LABEL: all_i64:
; V81:       @ %bb.0:
; V81-NEXT:    vstr fpcxtns, [sp, #-4]!
; V81-NEXT:    vscclrm {s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, vpr}
; V81-NEXT:    vldr fpcxtns, [sp], #4
; V81-NEXT:    clrm {r2, r3, r12, apsr}
; V81-NEXT:    bxns lr
  ret i64 %x
}

; With no clearing request, the CMSE expansion still copies LR.
define i32 @skip(i32 %x) "cmse_nonsecure_entry" "zero-call-used-regs"="skip" {
; BASE-LABEL: skip:
; BASE:       @ %bb.0:
; BASE-NEXT:    mov r1, lr
; BASE-NEXT:    mov r2, lr
; BASE-NEXT:    mov r3, lr
; BASE-NEXT:    mov r12, lr
; BASE-NEXT:    msr apsr, lr
; BASE-NEXT:    bxns lr
;
; MAIN-LABEL: skip:
; MAIN:       @ %bb.0:
; MAIN-NEXT:    mov r1, lr
; MAIN-NEXT:    mov r2, lr
; MAIN-NEXT:    mov r3, lr
; MAIN-NEXT:    mov r12, lr
; MAIN-NEXT:    msr apsr_nzcvq, lr
; MAIN-NEXT:    bxns lr
;
; FP-LABEL: skip:
; FP:       @ %bb.0:
; FP-NEXT:    mrs r12, control
; FP-NEXT:    tst.w r12, #8
; FP-NEXT:    beq .LBB4_2
; FP-NEXT:  @ %bb.1:
; FP-NEXT:    vmrs r12, fpscr
; FP-NEXT:    vmov d0, lr, lr
; FP-NEXT:    vmov d1, lr, lr
; FP-NEXT:    vmov d2, lr, lr
; FP-NEXT:    vmov d3, lr, lr
; FP-NEXT:    vmov d4, lr, lr
; FP-NEXT:    vmov d5, lr, lr
; FP-NEXT:    vmov d6, lr, lr
; FP-NEXT:    vmov d7, lr, lr
; FP-NEXT:    bic r12, r12, #159
; FP-NEXT:    bic r12, r12, #4026531840
; FP-NEXT:    vmsr fpscr, r12
; FP-NEXT:  .LBB4_2:
; FP-NEXT:    mov r1, lr
; FP-NEXT:    mov r2, lr
; FP-NEXT:    mov r3, lr
; FP-NEXT:    mov r12, lr
; FP-NEXT:    msr apsr_nzcvq, lr
; FP-NEXT:    bxns lr
;
; FP-O0-LABEL: skip:
; FP-O0:       @ %bb.0:
; FP-O0-NEXT:    mrs r12, control
; FP-O0-NEXT:    tst.w r12, #8
; FP-O0-NEXT:    beq .LBB4_2
; FP-O0-NEXT:  @ %bb.1:
; FP-O0-NEXT:    vmov d0, lr, lr
; FP-O0-NEXT:    vmov d1, lr, lr
; FP-O0-NEXT:    vmov d2, lr, lr
; FP-O0-NEXT:    vmov d3, lr, lr
; FP-O0-NEXT:    vmov d4, lr, lr
; FP-O0-NEXT:    vmov d5, lr, lr
; FP-O0-NEXT:    vmov d6, lr, lr
; FP-O0-NEXT:    vmov d7, lr, lr
; FP-O0-NEXT:    vmrs r12, fpscr
; FP-O0-NEXT:    bic r12, r12, #159
; FP-O0-NEXT:    bic r12, r12, #4026531840
; FP-O0-NEXT:    vmsr fpscr, r12
; FP-O0-NEXT:  .LBB4_2:
; FP-O0-NEXT:    mov r1, lr
; FP-O0-NEXT:    mov r2, lr
; FP-O0-NEXT:    mov r3, lr
; FP-O0-NEXT:    mov r12, lr
; FP-O0-NEXT:    msr apsr_nzcvq, lr
; FP-O0-NEXT:    bxns lr
;
; V81-LABEL: skip:
; V81:       @ %bb.0:
; V81-NEXT:    vstr fpcxtns, [sp, #-4]!
; V81-NEXT:    vscclrm {s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, vpr}
; V81-NEXT:    vldr fpcxtns, [sp], #4
; V81-NEXT:    clrm {r1, r2, r3, r12, apsr}
; V81-NEXT:    bxns lr
  ret i32 %x
}
