; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=armv7-unknown-linux-gnueabi -verify-machineinstrs < %s | FileCheck %s --check-prefix=ARM
; RUN: llc -mtriple=thumbv7m-none-eabi -verify-machineinstrs < %s | FileCheck %s --check-prefix=THUMB2
; RUN: llc -mtriple=armv7-unknown-linux-gnueabi -pei-print-clearing-sequence < %s -o /dev/null 2>&1 | FileCheck %s --check-prefix=SEQ

; Whether the register clear runs is decided for the function, but which
; registers it covers is decided at each exit. The tail call needs r0 and r1
; as arguments and clears only r2; the return keeps r0 as its result and
; clears r1 and r2. If-conversion runs after PEI and predicates the return's
; clears together with its bx, so they still run exactly when that exit does.

; SEQ-LABEL:  clearing sequence for function 'two_exits':
; SEQ-NEXT:   %bb.1 tail-call: clear-stack=not-requested clear-registers=emitted clear-flags=unimplemented
; SEQ-NEXT:   %bb.2 return: clear-stack=not-requested clear-registers=emitted clear-flags=unimplemented
; SEQ-NEXT:   end clearing sequence for function 'two_exits'

declare i32 @callee(i32, i32)

define i32 @two_exits(i1 %c, i32 %a, i32 %b) "zero-call-used-regs"="used-gpr" {
; ARM-LABEL: two_exits:
; ARM:       @ %bb.0: @ %entry
; ARM-NEXT:    tst r0, #1
; ARM-NEXT:    addeq r0, r1, r2
; ARM-NEXT:    moveq r1, #0
; ARM-NEXT:    moveq r2, #0
; ARM-NEXT:    bxeq lr
; ARM-NEXT:  .LBB0_1: @ %tail
; ARM-NEXT:    mov r0, r1
; ARM-NEXT:    mov r1, r2
; ARM-NEXT:    mov r2, #0
; ARM-NEXT:    b callee
;
; THUMB2-LABEL: two_exits:
; THUMB2:       @ %bb.0: @ %entry
; THUMB2-NEXT:    lsls r0, r0, #31
; THUMB2-NEXT:    itttt eq
; THUMB2-NEXT:    addeq r0, r1, r2
; THUMB2-NEXT:    moveq r1, #0
; THUMB2-NEXT:    moveq r2, #0
; THUMB2-NEXT:    bxeq lr
; THUMB2-NEXT:  .LBB0_1: @ %tail
; THUMB2-NEXT:    mov r0, r1
; THUMB2-NEXT:    mov r1, r2
; THUMB2-NEXT:    movs r2, #0
; THUMB2-NEXT:    b callee
entry:
  br i1 %c, label %tail, label %plain

tail:
  %r = tail call i32 @callee(i32 %a, i32 %b)
  ret i32 %r

plain:
  %s = add i32 %a, %b
  ret i32 %s
}
