; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Each group below performs the same write over the same dying object with four
; different intrinsics, in the three situations dead store elimination handles:
; dead at the end of a function, fully overwritten by a later write, and dead at
; the end of the object's lifetime.
;
; A plain memset is removed in all three. llvm.zeroize survives all three, both
; under dead store elimination on its own and under a full pipeline.
;
; The volatile rows are the control that keeps this file honest. A volatile
; memset and a volatile llvm.memset.inline also survive all three:
; DSEState::isRemovable refuses to remove a volatile memory intrinsic
; unconditionally, so at the IR level surviving dead store elimination does not
; distinguish llvm.zeroize from a volatile memory intrinsic. That distinction is
; not made here and this file should not be read as making it.
;
; What llvm.zeroize has over the volatile alternatives is a lowering guarantee:
; a volatile memset over a dynamic or large length lowers to a memset libcall,
; which spills the values live across the clear and grows the frame, while
; llvm.zeroize expands in place. That is not an IR-level property, so it is
; pinned by the X86 lowering test rather than by this one.
;
; Two things this file does show bear on that. llvm.zeroize needs no volatile
; marker to survive, so it stays a plain analyzable write to its region rather
; than an opaque one. And the memset_inline rows record that SROA rewrites
; llvm.memset.inline into a plain llvm.memset under the full pipeline, on
; exactly the kind of non-escaping stack buffer this feature targets, which is
; how the no-libcall guarantee is lost before code generation sees it.

; RUN: opt < %s -aa-pipeline=basic-aa -passes=dse -S | FileCheck %s
; RUN: opt < %s -passes='default<O2>' -S | FileCheck %s --check-prefix=O2

declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1)
declare void @llvm.memset.inline.p0.i64(ptr nocapture writeonly, i8, i64, i1)
declare void @llvm.zeroize.p0.i64(ptr nocapture writeonly, i64)

;; The object dies at the return and never escaped, so nothing can read any of
;; these writes.

define void @memset_at_end_of_function() {
; CHECK-LABEL: define void @memset_at_end_of_function() {
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_at_end_of_function(
; O2-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.memset.p0.i64(ptr %buf, i8 0, i64 16, i1 false)
  ret void
}

define void @volatile_memset_at_end_of_function() {
; CHECK-LABEL: define void @volatile_memset_at_end_of_function() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[BUF]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @volatile_memset_at_end_of_function(
; O2-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.memset.p0.i64(ptr align 1 [[BUF]], i8 0, i64 16, i1 true)
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.memset.p0.i64(ptr %buf, i8 0, i64 16, i1 true)
  ret void
}

define void @memset_inline_at_end_of_function() {
; CHECK-LABEL: define void @memset_inline_at_end_of_function() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.memset.inline.p0.i64(ptr [[BUF]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_inline_at_end_of_function(
; O2-SAME: ) local_unnamed_addr #[[ATTR3]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.memset.p0.i64(ptr align 1 [[BUF]], i8 0, i64 16, i1 true)
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.memset.inline.p0.i64(ptr %buf, i8 0, i64 16, i1 true)
  ret void
}

define void @zeroize_at_end_of_function() {
; CHECK-LABEL: define void @zeroize_at_end_of_function() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.zeroize.p0.i64(ptr [[BUF]], i64 16)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @zeroize_at_end_of_function(
; O2-SAME: ) local_unnamed_addr #[[ATTR4:[0-9]+]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.zeroize.p0.i64(ptr nonnull [[BUF]], i64 16)
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.zeroize.p0.i64(ptr %buf, i64 16)
  ret void
}

;; A later write covers exactly the same bytes.

define void @memset_overwritten(ptr %p) {
; CHECK-LABEL: define void @memset_overwritten(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 1, i64 16, i1 false)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_overwritten(
; O2-SAME: ptr nofree writeonly captures(none) initializes((0, 16)) [[P:%.*]]) local_unnamed_addr #[[ATTR5:[0-9]+]] {
; O2-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(16) [[P]], i8 1, i64 16, i1 false)
; O2-NEXT:    ret void
;
  call void @llvm.memset.p0.i64(ptr %p, i8 0, i64 16, i1 false)
  call void @llvm.memset.p0.i64(ptr %p, i8 1, i64 16, i1 false)
  ret void
}

define void @volatile_memset_overwritten(ptr %p) {
; CHECK-LABEL: define void @volatile_memset_overwritten(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 1, i64 16, i1 false)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @volatile_memset_overwritten(
; O2-SAME: ptr nofree writeonly captures(address) [[P:%.*]]) local_unnamed_addr #[[ATTR6:[0-9]+]] {
; O2-NEXT:    tail call void @llvm.memset.p0.i64(ptr [[P]], i8 0, i64 16, i1 true)
; O2-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(16) [[P]], i8 1, i64 16, i1 false)
; O2-NEXT:    ret void
;
  call void @llvm.memset.p0.i64(ptr %p, i8 0, i64 16, i1 true)
  call void @llvm.memset.p0.i64(ptr %p, i8 1, i64 16, i1 false)
  ret void
}

define void @memset_inline_overwritten(ptr %p) {
; CHECK-LABEL: define void @memset_inline_overwritten(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.memset.inline.p0.i64(ptr [[P]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 1, i64 16, i1 false)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_inline_overwritten(
; O2-SAME: ptr nofree writeonly captures(address) [[P:%.*]]) local_unnamed_addr #[[ATTR6]] {
; O2-NEXT:    tail call void @llvm.memset.inline.p0.i64(ptr [[P]], i8 0, i64 16, i1 true)
; O2-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(16) [[P]], i8 1, i64 16, i1 false)
; O2-NEXT:    ret void
;
  call void @llvm.memset.inline.p0.i64(ptr %p, i8 0, i64 16, i1 true)
  call void @llvm.memset.p0.i64(ptr %p, i8 1, i64 16, i1 false)
  ret void
}

define void @zeroize_overwritten(ptr %p) {
; CHECK-LABEL: define void @zeroize_overwritten(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    call void @llvm.zeroize.p0.i64(ptr [[P]], i64 16)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[P]], i8 1, i64 16, i1 false)
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @zeroize_overwritten(
; O2-SAME: ptr nofree writeonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR7:[0-9]+]] {
; O2-NEXT:    tail call void @llvm.zeroize.p0.i64(ptr [[P]], i64 16)
; O2-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(16) [[P]], i8 1, i64 16, i1 false)
; O2-NEXT:    ret void
;
  call void @llvm.zeroize.p0.i64(ptr %p, i64 16)
  call void @llvm.memset.p0.i64(ptr %p, i8 1, i64 16, i1 false)
  ret void
}

;; The lifetime of the object ends immediately after the write.

define void @memset_before_lifetime_end() {
; CHECK-LABEL: define void @memset_before_lifetime_end() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[BUF]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[BUF]])
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_before_lifetime_end(
; O2-SAME: ) local_unnamed_addr #[[ATTR2]] {
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.lifetime.start.p0(ptr %buf)
  call void @llvm.memset.p0.i64(ptr %buf, i8 0, i64 16, i1 false)
  call void @llvm.lifetime.end.p0(ptr %buf)
  ret void
}

define void @volatile_memset_before_lifetime_end() {
; CHECK-LABEL: define void @volatile_memset_before_lifetime_end() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[BUF]])
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr [[BUF]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[BUF]])
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @volatile_memset_before_lifetime_end(
; O2-SAME: ) local_unnamed_addr #[[ATTR3]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[BUF]])
; O2-NEXT:    call void @llvm.memset.p0.i64(ptr align 1 [[BUF]], i8 0, i64 16, i1 true)
; O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[BUF]])
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.lifetime.start.p0(ptr %buf)
  call void @llvm.memset.p0.i64(ptr %buf, i8 0, i64 16, i1 true)
  call void @llvm.lifetime.end.p0(ptr %buf)
  ret void
}

define void @memset_inline_before_lifetime_end() {
; CHECK-LABEL: define void @memset_inline_before_lifetime_end() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[BUF]])
; CHECK-NEXT:    call void @llvm.memset.inline.p0.i64(ptr [[BUF]], i8 0, i64 16, i1 true)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[BUF]])
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @memset_inline_before_lifetime_end(
; O2-SAME: ) local_unnamed_addr #[[ATTR3]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[BUF]])
; O2-NEXT:    call void @llvm.memset.p0.i64(ptr align 1 [[BUF]], i8 0, i64 16, i1 true)
; O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[BUF]])
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.lifetime.start.p0(ptr %buf)
  call void @llvm.memset.inline.p0.i64(ptr %buf, i8 0, i64 16, i1 true)
  call void @llvm.lifetime.end.p0(ptr %buf)
  ret void
}

define void @zeroize_before_lifetime_end() {
; CHECK-LABEL: define void @zeroize_before_lifetime_end() {
; CHECK-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[BUF]])
; CHECK-NEXT:    call void @llvm.zeroize.p0.i64(ptr [[BUF]], i64 16)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[BUF]])
; CHECK-NEXT:    ret void
;
; O2-LABEL: define void @zeroize_before_lifetime_end(
; O2-SAME: ) local_unnamed_addr #[[ATTR4]] {
; O2-NEXT:    [[BUF:%.*]] = alloca [16 x i8], align 1
; O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[BUF]])
; O2-NEXT:    call void @llvm.zeroize.p0.i64(ptr nonnull [[BUF]], i64 16)
; O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[BUF]])
; O2-NEXT:    ret void
;
  %buf = alloca [16 x i8], align 1
  call void @llvm.lifetime.start.p0(ptr %buf)
  call void @llvm.zeroize.p0.i64(ptr %buf, i64 16)
  call void @llvm.lifetime.end.p0(ptr %buf)
  ret void
}

declare void @llvm.lifetime.start.p0(ptr nocapture)
declare void @llvm.lifetime.end.p0(ptr nocapture)
