; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; Both selectors lower llvm.zeroize to a clearing sequence that is still there
; at the end of the pipeline, in the situations where an ordinary store covering
; the same bytes is removed.
;
; The clear is an opaque pseudo until emission, so there is no store to find at
; any point where something looks for one to remove.

; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s --check-prefix=SDAG
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs -global-isel -global-isel-abort=1 < %s | FileCheck %s --check-prefix=GISEL

declare void @llvm.zeroize.p0.i32(ptr nocapture writeonly, i32)
declare void @llvm.zeroize.p0.i64(ptr nocapture writeonly, i64)
declare void @llvm.lifetime.start.p0(ptr nocapture)
declare void @llvm.lifetime.end.p0(ptr nocapture)

define void @zeroize_dynamic_length(ptr %p, i64 %n) {
; SDAG-LABEL: zeroize_dynamic_length:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq %rsi, %rcx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_dynamic_length:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movq %rsi, %rcx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i64(ptr %p, i64 %n)
  ret void
}

define void @zeroize_constant_length(ptr %p) {
; SDAG-LABEL: zeroize_constant_length:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movl $32, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_constant_length:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movl $32, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i64(ptr %p, i64 32)
  ret void
}

;; A narrower count is zero-extended. A wider one is narrowed if it provably
;; fits and rejected otherwise; see zeroize-lowering.ll.
define void @zeroize_narrow_length(ptr %p, i32 %n) {
; SDAG-LABEL: zeroize_narrow_length:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movl %esi, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_narrow_length:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movl %esi, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i32(ptr %p, i32 %n)
  ret void
}

;; A store to the same bytes is dead once a later store covers it, and is
;; removed. The clear covering the same bytes is not.

define void @store_then_overwritten(ptr %p) {
; SDAG-LABEL: store_then_overwritten:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq $1, (%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: store_then_overwritten:
; GISEL:       # %bb.0:
; GISEL-NEXT:    xorl %eax, %eax
; GISEL-NEXT:    movl $1, %ecx
; GISEL-NEXT:    movq %rax, (%rdi)
; GISEL-NEXT:    movq %rcx, (%rdi)
; GISEL-NEXT:    retq
  store i64 0, ptr %p
  store i64 1, ptr %p
  ret void
}

define void @zeroize_then_overwritten(ptr %p) {
; SDAG-LABEL: zeroize_then_overwritten:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq %rdi, %rdx
; SDAG-NEXT:    movl $8, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    movq $1, (%rdx)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_then_overwritten:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movq %rdi, %rdx
; GISEL-NEXT:    movl $1, %esi
; GISEL-NEXT:    movl $8, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    movq %rsi, (%rdx)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i64(ptr %p, i64 8)
  store i64 1, ptr %p
  ret void
}

;; The second of two identical stores is redundant and one of them is removed.
;; Two clears of the same region are both performed.

define void @store_twice(ptr %p) {
; SDAG-LABEL: store_twice:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq $0, (%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: store_twice:
; GISEL:       # %bb.0:
; GISEL-NEXT:    xorl %eax, %eax
; GISEL-NEXT:    movq %rax, (%rdi)
; GISEL-NEXT:    movq %rax, (%rdi)
; GISEL-NEXT:    retq
  store i64 0, ptr %p
  store i64 0, ptr %p
  ret void
}

define void @zeroize_twice(ptr %p) {
; SDAG-LABEL: zeroize_twice:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq %rdi, %rdx
; SDAG-NEXT:    movl $8, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    movl $8, %ecx
; SDAG-NEXT:    movq %rdx, %rdi
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_twice:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movq %rdi, %rdx
; GISEL-NEXT:    movl $8, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    movl $8, %ecx
; GISEL-NEXT:    movq %rdx, %rdi
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i64(ptr %p, i64 8)
  call void @llvm.zeroize.p0.i64(ptr %p, i64 8)
  ret void
}

;; A store inside the cleared region but not at its start. This is what breaks
;; if the intrinsic node's memory operand ever lets alias analysis conclude the
;; clear is only as wide as its memory VT.
define void @store_inside_cleared_region(ptr %p) {
; SDAG-LABEL: store_inside_cleared_region:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movq %rdi, %rdx
; SDAG-NEXT:    movl $32, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    movq $1, 24(%rdx)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: store_inside_cleared_region:
; GISEL:       # %bb.0:
; GISEL-NEXT:    movq %rdi, %rdx
; GISEL-NEXT:    movl $1, %esi
; GISEL-NEXT:    movl $32, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    movq %rsi, 24(%rdx)
; GISEL-NEXT:    retq
  call void @llvm.zeroize.p0.i64(ptr %p, i64 32)
  %q = getelementptr i8, ptr %p, i64 24
  store i64 1, ptr %q
  ret void
}

;; The object never escapes and dies at the return.
define void @zeroize_dying_alloca() {
; SDAG-LABEL: zeroize_dying_alloca:
; SDAG:       # %bb.0:
; SDAG-NEXT:    leaq -{{[0-9]+}}(%rsp), %rdi
; SDAG-NEXT:    movl $32, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_dying_alloca:
; GISEL:       # %bb.0:
; GISEL-NEXT:    leaq -{{[0-9]+}}(%rsp), %rdi
; GISEL-NEXT:    movl $32, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  %buf = alloca [32 x i8], align 16
  call void @llvm.zeroize.p0.i64(ptr %buf, i64 32)
  ret void
}

;; The lifetime of the object ends immediately after the clear.
define void @zeroize_before_lifetime_end() {
; SDAG-LABEL: zeroize_before_lifetime_end:
; SDAG:       # %bb.0:
; SDAG-NEXT:    leaq -{{[0-9]+}}(%rsp), %rdi
; SDAG-NEXT:    movl $32, %ecx
; SDAG-NEXT:    movl $0, %eax
; SDAG-NEXT:    rep;stosb %al, %es:(%rdi)
; SDAG-NEXT:    retq
;
; GISEL-LABEL: zeroize_before_lifetime_end:
; GISEL:       # %bb.0:
; GISEL-NEXT:    leaq -{{[0-9]+}}(%rsp), %rdi
; GISEL-NEXT:    movl $32, %ecx
; GISEL-NEXT:    movl $0, %eax
; GISEL-NEXT:    rep;stosb %al, %es:(%rdi)
; GISEL-NEXT:    retq
  %buf = alloca [32 x i8], align 16
  call void @llvm.lifetime.start.p0(ptr %buf)
  call void @llvm.zeroize.p0.i64(ptr %buf, i64 32)
  call void @llvm.lifetime.end.p0(ptr %buf)
  ret void
}
